# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

[profile.release]
lto = true
codegen-units = 1

[workspace]
members = [
    "bdd/rust",
    "core/bench",
    "core/bench/dashboard/frontend",
    "core/bench/dashboard/server",
    "core/bench/dashboard/shared",
    "core/bench/report",
    "core/bench/runner",
    "core/binary_protocol",
    "core/cli",
    "core/common",
    "core/connectors/runtime",
    "core/connectors/sdk",
    "core/connectors/sinks/postgres_sink",
    "core/connectors/sinks/quickwit_sink",
    "core/connectors/sinks/stdout_sink",
    "core/connectors/sources/postgres_source",
    "core/connectors/sources/random_source",
    "core/integration",
    "core/sdk",
    "core/server",
    "core/tools",
    "examples/rust",
]
exclude = ["foreign/python"]
resolver = "2"

[workspace.dependencies]
ahash = { version = "0.8.12", features = ["serde"] }
anyhow = "1.0.98"
async-broadcast = "0.7.2"
async-dropper = { version = "0.3.1", features = ["tokio", "simple"] }
async-trait = "0.1.88"
async_zip = { version = "0.0.17", features = [
    "tokio",
    "lzma",
    "bzip2",
    "xz",
    "deflate",
    "zstd",
] }
axum = "0.8.4"
axum-server = { version = "0.7.2", features = ["tls-rustls"] }
bcrypt = "0.17.0"
bincode = { version = "2.0.1", features = ["serde"] }
blake3 = "1.8.2"
bon = "3.6.4"
byte-unit = { version = "5.1.6", default-features = false, features = [
    "serde",
    "byte",
    "std",
] }
bytes = "1.10.1"
charming = "0.6.0"
chrono = { version = "0.4.41", features = ["serde"] }
clap = { version = "4.5.40", features = ["derive"] }
config = { version = "0.15.11" }
comfy-table = "7.1.4"
crc32fast = "1.4.2"
crossbeam = "0.8.4"
cyper = "0.4.0"
dashmap = "6.1.0"
derive_builder = "0.20.2"
derive_more = { version = "2.0.1", features = ["full"] }
derive-new = "0.7.0"
dirs = "6.0.0"
dlopen2 = "0.8.0"
dotenvy = "0.15.7"
enum_dispatch = "0.3.13"
figlet-rs = "0.1.5"
flume = "0.11.1"
async-channel = "2.3.1"
futures = "0.3.31"
futures-util = "0.3.31"
human-repr = "1.1.0"
humantime = "2.2.0"
keyring = { version = "3.6.2", features = ["sync-secret-service", "vendored"] }
nonzero_lit = "0.1.2"
once_cell = "1.21.3"
passterm = "=2.0.1"
quinn = "0.11.8"
postcard = { version = "1.1.1", features = ["alloc"] }
rand = "0.9.1"
reqwest = { version = "0.12.20", default-features = false, features = [
    "json",
    "rustls-tls",
] }
reqwest-middleware = { version = "0.4.2", features = ["json"] }
reqwest-retry = "0.7.0"
rustls = { version = "0.23.28", features = ["ring"] }
serde = { version = "1.0.219", features = ["derive", "rc"] }
serde_json = "1.0.140"
serde_with = { version = "3.13.0", features = ["base64", "macros"] }
serde_yml = "0.0.12"
serial_test = "3.2.0"
simd-json = { version = "0.15.1", features = ["serde_impl"] }
sysinfo = "0.35.2"
tempfile = "3.20.0"
thiserror = "2.0.12"
tokio = { version = "1.45.1", features = ["full"] }
compio =  { git = "https://github.com/compio-rs/compio.git", rev = "fe4243f0b6811ebc325afd081c9b087b4d9817be", features = ["runtime", "macros", "io-uring", "time", "rustls"] }
cyper = { version = "0.4.0", features = ["rustls"], default-features = false}
tokio-rustls = "0.26.2"
toml = "0.8.23"
tracing = "0.1.41"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.19", default-features = false, features = [
    "fmt",
    "env-filter",
    "ansi",
] }
uuid = { version = "1.17.0", features = [
    "v4",
    "v7",
    "fast-rng",
    "serde",
    "zerocopy",
] }
rust-s3 = { version = "0.36.0-beta.2", default-features = false, features = [
    "tokio-rustls-tls",
    "tags",
] }
strum = { version = "0.27.1", features = ["derive"] }
strum_macros = "0.27.1"
aes-gcm = "0.10.3"
base64 = "0.22.1"
twox-hash = { version = "2.1.1", features = ["xxhash32"] }

# Common dependencies across multiple packages
colored = "3.0.0"
env_logger = "0.11.8"
lazy_static = "1.5.0"
log = "0.4.27"
mockall = "0.13.1"
predicates = "3.1.3"
regex = "1.11.1"
test-case = "3.3.1"
tokio-util = { version = "0.7.15", features = ["compat"] }
tower-http = { version = "0.6.6", features = [
    "add-extension",
    "cors",
    "trace",
] }
trait-variant = "0.1.2"
webpki-roots = "1.0.1"
zip = "4.2.0"

# Optional dependencies
mimalloc = "0.1"
console-subscriber = "0.4.1"

# Path dependencies
iggy_binary_protocol = { path = "core/binary_protocol", version = "0.7.0" }
iggy_common = { path = "core/common", version = "0.7.0" }
iggy_connector_sdk = { path = "core/connectors/sdk", version = "0.1.0" }
iggy = { path = "core/sdk", version = "0.7.0" }
server = { path = "core/server" }
integration = { path = "core/integration" }
bench-report = { path = "core/bench/report" }
bench-runner = { path = "core/bench/runner" }
bench-dashboard-frontend = { path = "core/bench/dashboard/frontend" }
bench-dashboard-server = { path = "core/bench/dashboard/server" }
bench-dashboard-shared = { path = "core/bench/dashboard/shared" }
